application: cptflairbot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /style\.css
  static_files: style.css
  upload: style\.css

- url: /cptflairbot
  script: cron.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"
